export const COPY = {
  sk: {
    nav: {
      services: "Služby",
      work: "Ako pracujeme",
      contact: "Kontakt",
      cta: "Začať projekt",
    },
    hero: {
      eyebrow: "Digitálne štúdio pre reality",
      title: ["Obsah, ktorý", "predáva ešte", "predtým, než", "klient príde."],
      titleMuted: 3,
      sub: "Tvoríme weby, cinematic videá a digitálnu premenu priestorov pre realitných agentov a developerov. Prémiová prezentácia, ktorá skráti cestu od inzerátu k podpisu.",
      ctaPrimary: "Nezáväzný dopyt",
      ctaSecondary: "Pozrieť služby",
      stats: [
        { num: "48h", lbl: "priemerné dodanie ukážky" },
        { num: "3", lbl: "prepojené služby pod jednou strechou" },
        { num: "1 foto", lbl: "stačí na premenu priestoru" },
      ],
    },
    showcase: {
      tag: "Ukážka / Digitálna premena",
      title: "Z jednej fotky holej miestnosti — cinematic pred a po.",
      desc: "Pošlete nám fotku prázdneho alebo rozostavaného priestoru. My z nej vytvoríme plynulé video, v ktorom sa miestnosť premení na plne zariadený domov. Bez fotografa navyše, bez zariaďovania, bez čakania.",
      points: [
        "Stačí jedna fotka priestoru",
        "Plynulá premena z holej na zariadenú",
        "Štýl interiéru na mieru cieľovému kupujúcemu",
        "Výstup pre Instagram, TikTok aj portály",
      ],
      badge: "Náhľad",
      stages: ["Prázdny priestor", "Premena", "Zariadený domov"],
      hint: "Scrollujte a sledujte premenu",
    },
    services: {
      eyebrow: "Čo ponúkame",
      title: "Tri služby, ktoré spolu tvoria kompletnú prezentáciu.",
      lead: "Nemusíte zháňať web štúdio, kameramana a stagera zvlášť. Máte to na jednom mieste — konzistentné a rýchle.",
      cards: [
        {
          num: "01",
          title: "Tvorba webstránok",
          desc: "Moderné, rýchle a plne responzívne weby pre realitné kancelárie a developerské projekty. Od landing page po kompletný katalóg nehnuteľností.",
          meta: ["Responzívny dizajn", "SEO základ", "Rýchle načítanie"],
        },
        {
          num: "02",
          title: "Cinematic videá",
          desc: "Filmové video obhliadky a UGC obsah, ktorý pôsobí ako odporúčanie, nie ako reklama. Natočené alebo vytvorené z vašich podkladov.",
          meta: ["Video obhliadky", "Strih a titulky", "Formáty pre platformy"],
        },
        {
          num: "03",
          title: "Digitálna premena priestorov",
          desc: "Prázdne priestory premeníme na zariadené — vo fotke aj vo videu. Kupujúci uvidí potenciál a život, nie holé steny.",
          meta: ["Z jednej fotky", "Pred a po", "Štýl na mieru"],
        },
      ],
    },
    process: {
      eyebrow: "Ako pracujeme",
      title: "Priamočaro. Od nápadu k hotovému obsahu.",
      steps: [
        { num: "01", title: "Konzultácia", desc: "Krátky call, kde zistíme, čo predávate a komu. Navrhneme najvhodnejší formát." },
        { num: "02", title: "Podklady", desc: "Pošlete nám fotky a informácie, alebo prídeme priamo na miesto. Zvyšok je na nás." },
        { num: "03", title: "Tvorba", desc: "Pripravíme web, video či premenu. Prvú ukážku vidíte spravidla do 48 hodín." },
        { num: "04", title: "Dodanie", desc: "Doladíme podľa vašej spätnej väzby a odovzdáme obsah pripravený na publikovanie." },
      ],
    },
    contact: {
      eyebrow: "Kontakt",
      title: "Povedzte nám, o čo máte záujem.",
      lead: "Pár klikov a sme v obraze. Do 24 hodín sa ozveme s konkrétnym návrhom — nezáväzne.",
      directTitle: "Priamy kontakt",
      form: {
        step1Q: "O ktorú službu máte záujem?",
        step1Help: "Vyberte jednu alebo viac — poradíme aj s kombináciou.",
        services: [
          "Tvorba webstránky",
          "Cinematic video",
          "Digitálna premena priestorov",
          "Kompletný balík",
        ],
        step2Q: "O aký typ nehnuteľnosti ide?",
        step2Help: "Pomôže nám to odhadnúť rozsah.",
        propertyTypes: [
          "Byt",
          "Dom",
          "Novostavba / projekt",
          "Komerčný priestor",
        ],
        step3Q: "Kam sa vám môžeme ozvať?",
        step3Help: "Vyplňte kontakt a prípadne pár slov k projektu.",
        name: "Meno a priezvisko",
        email: "Email",
        phone: "Telefón (nepovinné)",
        message: "Krátka správa (nepovinné)",
        messagePh: "Napríklad: mám 3 byty na predaj v centre…",
        step4Q: "Skontrolujte a odošlite",
        step4Help: "Ak sedí, odošlite dopyt. Ozveme sa do 24 hodín.",
        summaryService: "Služba",
        summaryType: "Nehnuteľnosť",
        summaryName: "Meno",
        summaryEmail: "Email",
        summaryPhone: "Telefón",
        back: "Späť",
        next: "Pokračovať",
        submit: "Odoslať dopyt",
        sending: "Odosielam…",
        doneTitle: "Dopyt odoslaný",
        doneText: "Ďakujeme. Ozveme sa vám do 24 hodín na zadaný kontakt.",
        errText: "Nepodarilo sa odoslať. Skúste znova alebo napíšte priamo na email.",
        stepOf: "Krok",
      },
    },
    footer: {
      tagline: "Digitálne riešenia pre reality.",
      colServices: "Služby",
      colContact: "Kontakt",
      services: ["Tvorba webstránok", "Cinematic videá", "Digitálna premena"],
      rights: "Všetky práva vyhradené.",
    },
  },

  en: {
    nav: {
      services: "Services",
      work: "How we work",
      contact: "Contact",
      cta: "Start a project",
    },
    hero: {
      eyebrow: "Digital studio for real estate",
      title: ["Content that", "sells before", "the buyer", "even arrives."],
      titleMuted: 2,
      sub: "We build websites, cinematic videos and digital space transformations for real estate agents and developers. Premium presentation that shortens the path from listing to signature.",
      ctaPrimary: "Get in touch",
      ctaSecondary: "See services",
      stats: [
        { num: "48h", lbl: "average preview turnaround" },
        { num: "3", lbl: "services under one roof" },
        { num: "1 photo", lbl: "is all it takes to transform a space" },
      ],
    },
    showcase: {
      tag: "Showcase / Digital transformation",
      title: "From one photo of an empty room — a cinematic before & after.",
      desc: "Send us a photo of an empty or unfinished space. We turn it into a smooth video where the room transforms into a fully furnished home. No extra photographer, no staging, no waiting.",
      points: [
        "A single photo is enough",
        "Smooth transition from bare to furnished",
        "Interior style tailored to the target buyer",
        "Output for Instagram, TikTok and portals",
      ],
      badge: "Preview",
      stages: ["Empty space", "Transforming", "Furnished home"],
      hint: "Scroll to watch the transformation",
    },
    services: {
      eyebrow: "What we offer",
      title: "Three services that together form a complete presentation.",
      lead: "No need to hire a web studio, a videographer and a stager separately. It's all in one place — consistent and fast.",
      cards: [
        {
          num: "01",
          title: "Website design",
          desc: "Modern, fast and fully responsive websites for real estate offices and development projects. From a landing page to a full property catalog.",
          meta: ["Responsive design", "SEO foundation", "Fast loading"],
        },
        {
          num: "02",
          title: "Cinematic videos",
          desc: "Cinematic tours and UGC content that feels like a recommendation, not an ad. Filmed or created from your materials.",
          meta: ["Video tours", "Editing & captions", "Platform formats"],
        },
        {
          num: "03",
          title: "Digital space transformation",
          desc: "We turn empty spaces into furnished ones — in photos and video. Buyers see potential and life, not bare walls.",
          meta: ["From one photo", "Before & after", "Custom style"],
        },
      ],
    },
    process: {
      eyebrow: "How we work",
      title: "Straightforward. From idea to finished content.",
      steps: [
        { num: "01", title: "Consultation", desc: "A short call to learn what you're selling and to whom. We suggest the best format." },
        { num: "02", title: "Materials", desc: "Send us photos and info, or we come on site. The rest is on us." },
        { num: "03", title: "Creation", desc: "We build the website, video or transformation. First preview usually within 48 hours." },
        { num: "04", title: "Delivery", desc: "We refine based on your feedback and hand over content ready to publish." },
      ],
    },
    contact: {
      eyebrow: "Contact",
      title: "Tell us what you're interested in.",
      lead: "A few clicks and we're up to speed. We'll reply within 24 hours with a concrete proposal — no obligation.",
      directTitle: "Direct contact",
      form: {
        step1Q: "Which service are you interested in?",
        step1Help: "Pick one or more — we can advise on combinations too.",
        services: [
          "Website design",
          "Cinematic video",
          "Digital space transformation",
          "Complete package",
        ],
        step2Q: "What type of property is it?",
        step2Help: "This helps us estimate the scope.",
        propertyTypes: [
          "Apartment",
          "House",
          "New build / project",
          "Commercial space",
        ],
        step3Q: "How can we reach you?",
        step3Help: "Fill in your contact and a few words about the project.",
        name: "Full name",
        email: "Email",
        phone: "Phone (optional)",
        message: "Short message (optional)",
        messagePh: "For example: I have 3 apartments for sale downtown…",
        step4Q: "Review and send",
        step4Help: "If it looks right, send your inquiry. We'll reply within 24 hours.",
        summaryService: "Service",
        summaryType: "Property",
        summaryName: "Name",
        summaryEmail: "Email",
        summaryPhone: "Phone",
        back: "Back",
        next: "Continue",
        submit: "Send inquiry",
        sending: "Sending…",
        doneTitle: "Inquiry sent",
        doneText: "Thank you. We'll get back to you within 24 hours.",
        errText: "Couldn't send. Please try again or email us directly.",
        stepOf: "Step",
      },
    },
    footer: {
      tagline: "Digital solutions for real estate.",
      colServices: "Services",
      colContact: "Contact",
      services: ["Website design", "Cinematic videos", "Digital transformation"],
      rights: "All rights reserved.",
    },
  },
};
